[project]
name = "task-manager"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "django>=6.1.1",
    "djangorestframework>=3.18.1",
    "djangorestframework-simplejwt>=5.5.1",
    "drf-spectacular>=0.30.0",
    "gunicorn>=26.2.0",
    "psycopg[binary]>=3.3.5",
    "python-dotenv>=1.2.3",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-django>=4.14.0",
    "ruff>=0.16.7",
]

[tool.ruff]
line-length = 88
target-version = "py313"

[tool.ruff.lint]
select = [
    "UP",
    "I",
    "E",
    "W",
    "F",
    "B",
    "C4",
    "S",
    "BLE",
    "T20",
    "T10",
    "PT",
    "RUF",
    "DTZ",
    "ERA",
    "FURB",
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"

[tool.ruff.lint.per-file-ignores]
"tests/**/test_*.py" = ["S101"]
"**/migrations/*.py" = ["RUF012"]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "app.settings"
addopts = "--reuse-db"
python_files = ["test_*.py"]
testpaths = ["tests"]
